services:
  - type: web
    name: python-learning-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:main --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: python-learning-bot
          envVarKey: RENDER_EXTERNAL_URL
